# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        #MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuMaster = QtWidgets.QMenu(self.menubar)
        self.menuMaster.setObjectName("menuMaster")
        self.menuTransaction = QtWidgets.QMenu(self.menubar)
        self.menuTransaction.setObjectName("menuTransaction")
        self.menuDispatch = QtWidgets.QMenu(self.menubar)
        self.menuDispatch.setObjectName("menuDispatch")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCreate_Transaction = QtWidgets.QAction(MainWindow)
        self.actionCreate_Transaction.setObjectName("actionCreate_Transaction")
        self.actionCommulative_sale = QtWidgets.QAction(MainWindow)
        self.actionCommulative_sale.setObjectName("actionCommulative_sale")
        self.actionPayment_Transaction = QtWidgets.QAction(MainWindow)
        self.actionPayment_Transaction.setObjectName("actionPayment_Transaction")
        self.actionPlant_to_Godown = QtWidgets.QAction(MainWindow)
        self.actionPlant_to_Godown.setObjectName("actionPlant_to_Godown")
        self.actionBank_Master = QtWidgets.QAction(MainWindow)
        self.actionBank_Master.setObjectName("actionBank_Master")
        self.actionItem_Master = QtWidgets.QAction(MainWindow)
        self.actionItem_Master.setObjectName("actionItem_Master")
        self.actionCustomer_Master = QtWidgets.QAction(MainWindow)
        self.actionCustomer_Master.setObjectName("actionCustomer_Master")
        self.actionItem_Batch_Info = QtWidgets.QAction(MainWindow)
        self.actionItem_Batch_Info.setObjectName("actionItem_Batch_Info")
        self.actionEnquiry = QtWidgets.QAction(MainWindow)
        self.actionEnquiry.setObjectName("actionEnquiry")
        self.actionItem_Return = QtWidgets.QAction(MainWindow)
        self.actionItem_Return.setObjectName("actionItem_Return")
        self.menuMaster.addAction(self.actionBank_Master)
        self.menuMaster.addAction(self.actionItem_Master)
        self.menuMaster.addAction(self.actionCustomer_Master)
        self.menuMaster.addAction(self.actionItem_Batch_Info)
        self.menuTransaction.addAction(self.actionCreate_Transaction)
        self.menuTransaction.addAction(self.actionCommulative_sale)
        self.menuTransaction.addAction(self.actionPayment_Transaction)
        self.menuTransaction.addAction(self.actionPlant_to_Godown)
        self.menuDispatch.addAction(self.actionEnquiry)
        self.menuDispatch.addAction(self.actionItem_Return)
        self.menubar.addAction(self.menuMaster.menuAction())
        self.menubar.addAction(self.menuTransaction.menuAction())
        self.menubar.addAction(self.menuDispatch.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuMaster.setTitle(_translate("MainWindow", "Master"))
        self.menuTransaction.setTitle(_translate("MainWindow", "Transaction"))
        self.menuDispatch.setTitle(_translate("MainWindow", "Dispatch"))
        self.actionCreate_Transaction.setText(_translate("MainWindow", "Create Transaction"))
        self.actionCommulative_sale.setText(_translate("MainWindow", "Cumulative Sale"))
        self.actionPayment_Transaction.setText(_translate("MainWindow", "Payment Transaction"))
        self.actionPlant_to_Godown.setText(_translate("MainWindow", "Plant to Goadown"))
        self.actionBank_Master.setText(_translate("MainWindow", "Bank Master"))
        self.actionItem_Master.setText(_translate("MainWindow", "Item Master"))
        self.actionCustomer_Master.setText(_translate("MainWindow", "Customer Master"))
        self.actionItem_Batch_Info.setText(_translate("MainWindow", "Item Batch Info"))
        self.actionEnquiry.setText(_translate("MainWindow", "Enquiry"))
        self.actionItem_Return.setText(_translate("MainWindow", "Item Return"))
if __name__=="__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    widget = QtWidgets.QWidget()
    ui = Ui_MainWindow()
    ui.setupUi(widget)
    widget.show()
    sys.exit(app.exec_())